export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CURRENT_PHOTO = 'CURRENT_PHOTO';
export type CURRENT_PHOTO = typeof CURRENT_PHOTO;

export const OVERTURN_PHOTO = 'OVERTURN_PHOTO';
export type OVERTURN_PHOTO = typeof OVERTURN_PHOTO;
